language: node_js
node_js:
  - 11
services:
  - postgresql

before_script:
  - createdb jobly-test-users
  - psql jobly-test-users < data.sql
  - createdb jobly-test-jobs
  - psql jobly-test-jobs < data.sql
  - createdb jobly-test-companies
  - psql jobly-test-companies < data.sql
