language: node_js
node_js:
  - 11
services:
  - postgresql

before_script:
  - pg_restore -C -d postgres db.dump
  - createdb -T jobly-test jobly-test-jobs
  - createdb -T jobly-test jobly-test-companies
