language: node_js
node_js:
  - 11
services:
  - postgresql

before_script:
  - createdb jobly-test
  - psql -a jobly-test < db.sql
  - createdb -T jobly-test jobly-test-jobs
  - createdb -T jobly-test jobly-test-companies
