language: node_js
node_js:
  - 11
services:
  - postgresql

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12

before_script:
  - createdb jobly-test
  - pg_restore -C -c -O -x -d jobly-test db.dump
  - createdb -T jobly-test jobly-test-jobs
  - createdb -T jobly-test jobly-test-companies
